channels:
  - conda-forge
  - pytorch
dependencies:
  - uproot
  - numpy
  - pandas
  - matplotlib
  - iminuit
  - scikit-learn
  - pytorch-cpu
  - numba
  - dask
  - python-graphviz
  - cython
  - pybind11
  - pillow
  - root
  - root_numpy
  - h5py
  - pyarrow
